git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/sctplib1@1787 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/make-deb b/make-deb
--- a/make-deb
+++ b/make-deb
@@ -47,8 +47,16 @@ if [ "$DISTRIBUTIONS" == "" ] ; then
 fi
 
 
-rm -f $PACKAGE-*.gz $PACKAGE"_"*.gz
-( ./bootstrap && ./configure $CONFOPT && make dist ) || exit 1
+UPSTREAM_PACKAGE="`find . -name $PACKAGE-*.gz`"
+UPSTREAM_PACKAGES=`find . -name $PACKAGE-*.gz | wc --lines`
+if [ "$UPSTREAM_PACKAGE" == "" ]; then
+  rm -f $PACKAGE-*.gz $PACKAGE"_"*.gz
+  ( ./bootstrap && ./configure $CONFOPT && make dist ) || exit 1
+elif [ $UPSTREAM_PACKAGES -ne 1 ] ; then
+   echo "ERROR: There are multiple upstream packages (from \"make dist\")!" >&2
+   echo "       Remove all except the actual version!" >&2
+   exit 1
+fi
 
 
 for DISTRIBUTION in $DISTRIBUTIONS ; do
